// Code generated by gommon from pkg/gommon.yml DO NOT EDIT.

package pkg

import dlog "github.com/dyweb/gommon/log"

func (srv *Server) SetLogger(logger *dlog.Logger) {
	srv.logger = logger
}

func (srv *Server) GetLogger() *dlog.Logger {
	return srv.logger
}

func (srv *Server) LoggerIdentity(justCallMe func() dlog.Identity) dlog.Identity {
	return justCallMe()
}
