// Code generated by gommon from ice/db/gommon.yml DO NOT EDIT.
package db

import dlog "github.com/dyweb/gommon/log"

func (mgr *Manager) SetLogger(logger *dlog.Logger) {
	mgr.log = logger
}

func (mgr *Manager) GetLogger() *dlog.Logger {
	return mgr.log
}

func (mgr *Manager) LoggerIdentity(justCallMe func() *dlog.Identity) *dlog.Identity {
	return justCallMe()
}

func (w *Wrapper) SetLogger(logger *dlog.Logger) {
	w.log = logger
}

func (w *Wrapper) GetLogger() *dlog.Logger {
	return w.log
}

func (w *Wrapper) LoggerIdentity(justCallMe func() *dlog.Identity) *dlog.Identity {
	return justCallMe()
}
