// Code generated by gommon from ice/transport/http/gommon.yml DO NOT EDIT.
package http

import dlog "github.com/dyweb/gommon/log"

func (srv *Server) SetLogger(logger *dlog.Logger) {
	srv.log = logger
}

func (srv *Server) GetLogger() *dlog.Logger {
	return srv.log
}

func (srv *Server) LoggerIdentity(justCallMe func() *dlog.Identity) *dlog.Identity {
	return justCallMe()
}
