// Code generated by gommon from _example/github/pkg/server/gommon.yml DO NOT EDIT.
package server

import dlog "github.com/dyweb/gommon/log"

func (app *App) SetLogger(logger *dlog.Logger) {
	app.log = logger
}

func (app *App) GetLogger() *dlog.Logger {
	return app.log
}

func (app *App) LoggerIdentity(justCallMe func() *dlog.Identity) *dlog.Identity {
	return justCallMe()
}
